### ISSUE TITLE
Puppet runall - issue with PQL discovery

### ISSUE THREAD

**Issue by m4ce** [ripienaar/mcollective-choria#131]
Not sure if I am doing anything wrong here ..

```
$ mco find -I "pql:nodes[certname] { certname ~ '^cpu.*' }"
cpu01
cpu02
cpu03
cpu04
...
```

Invoke puppet run:
```
$ mco puppet -I "pql:nodes[certname] { certname ~ '^cpu.*' }" runall 2
2017-01-06 14:32:33: Running all nodes with a concurrency of 2
2017-01-06 14:32:33: Discovering enabled Puppet nodes to manage
2017-01-06 14:32:36: Found 0 enabled nodes

No request sent, we did not discover any nodes.2017-01-06 14:32:36: Iteration complete. Initiated a Puppet run on 0 nodes.
```

Debug log:
```
D, [2017-01-06T14:32:33.337193 #21341] DEBUG -- : runnerstats.rb:38:in `validated' Incrementing validated stat
D, [2017-01-06T14:32:33.337301 #21341] DEBUG -- : pluginmanager.rb:83:in `[]' Returning cached plugin security_plugin with class MCollective::Security::Choria
D, [2017-01-06T14:32:33.338576 #21341] DEBUG -- : pluginmanager.rb:83:in `[]' Returning cached plugin security_plugin with class MCollective::Security::Choria
D, [2017-01-06T14:32:33.338792 #21341] DEBUG -- : base.rb:117:in `block (2 levels) in validate_filter?' Passing based on agent puppet
D, [2017-01-06T14:32:33.338905 #21341] DEBUG -- : base.rb:145:in `block in validate_filter?' Failed based on identity
D, [2017-01-06T14:32:33.339072 #21341] DEBUG -- : pluginmanager.rb:88:in `[]' Returning new plugin puppet_data with class MCollective::Data::Puppet_data
D, [2017-01-06T14:32:33.339362 #21341] DEBUG -- : cache.rb:105:in `read' Cache hit on 'ddl' key 'data/puppet_data'
D, [2017-01-06T14:32:33.339668 #21341] DEBUG -- : base.rb:25:in `lookup' Doing data query puppet_data for ''
D, [2017-01-06T14:32:33.342173 #21341] DEBUG -- : base.rb:106:in `block (2 levels) in validate_filter?' Passing based on class and fact composition
D, [2017-01-06T14:32:33.342301 #21341] DEBUG -- : base.rb:159:in `validate_filter?' Message failed the filter checks
D, [2017-01-06T14:32:33.342400 #21341] DEBUG -- : runnerstats.rb:32:in `filtered' Incrementing filtered stat
D, [2017-01-06T14:32:33.342512 #21341] DEBUG -- : runner.rb:196:in `rescue in block in receiver_thread' Message does not pass filters, ignoring
D, [2017-01-06T14:32:33.342605 #21341] DEBUG -- : nats.rb:224:in `receive' Waiting for a message from NATS
```

Looks like the filter is not passing the checks?

**Comment by m4ce** [comment]
By the way, I am using the latest 0.0.15.

**Comment by ripienaar** [comment]
```
D, [2017-01-06T14:32:33.338905 #21341] DEBUG -- : base.rb:145:in `block in validate_filter?' Failed based on identity
```

I wonder if somehow the PQL query makes it out over the network when it shouldnt, will need to debug a bit

**Comment by ripienaar** [comment]
Oh I get it, doh this wont work with runall.

Runall has very special needs for discovery and it makes a bunch of compound filters like -S ones, and those force the use of the traditional discovery method.  So the -I filter will go out as a old school filter.

You can do:

```
mco puppet runall 2 --dm=mc -I /^cpu/
```

and this should work, runall is a snowflake :(

**Comment by m4ce** [comment]
Ok, thanks for this. Just renamed the issue so that if other ppl have the issues, it's easier to find :)

**Comment by ripienaar** [comment]
no worries, runall needs a rewrite :)
