### ISSUE TITLE
The choria application failed to run: uninitialized constant MCollective::Util::Choria::Resolv

### ISSUE THREAD

**Issue by dnlsng** [ripienaar/mcollective-choria#59]
I'm testing this module with ActiveMQ for the middleware which is mostly working fine so far.

However, mco choria request_cert is failing.
```
$ mco choria request_cert -v
Certificate /home/<USER>/.puppetlabs/etc/puppet/ssl/certs/<USER>.mcollective.pem has already been requested, attempting to retrieve it
Waiting up to 240 seconds for it to be signed

Attempting to download certificate /home/<USER>/.puppetlabs/etc/puppet/ssl/certs/<USER>.mcollective.pem: 0 / 24
The choria application failed to run: uninitialized constant MCollective::Util::Choria::Resolv

uninitialized constant MCollective::Util::Choria::Resolv (NameError)
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:28:in `resolver'  <----
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:83:in `block in query_srv_records'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:82:in `map'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:82:in `query_srv_records'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:281:in `try_srv'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:315:in `puppetca_server'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:580:in `attempt_fetch_cert'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:117:in `block in request_cert_command'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:114:in `times'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:114:in `request_cert_command'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:78:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/bin/mco:33:in `<main>'
```

To get around it temporarily, I hacked `/opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb` with a `require "resolv"` at the top and that seemed to work fine.

**Comment by ripienaar** [comment]
interesting, wonder how this didnt surface either but yeah that sounds about right, feel like sending a PR?
