### ISSUE TITLE
Ruby error when using mcollective-package-agent: Could not autoload puppet/provider/service/windows: no 'environments'

### ISSUE THREAD

**Issue by masterzen** [ripienaar/mcollective-choria#86]
We just installed a brand new 1 node mcollective-choria system (ubuntu 16.04), and latest puppet-agent/puppetserver.

When we run the mcollective puppet agent, no problems, but if we try the mcollective service or package agent we get the following error:
~~~
error 2016/12/19 16:50:49: agent.rb:108:in `rescue in handlemsg' service#status failed: Puppet::Error: Could not autoload puppet/type/service: Could not autoload puppet/provider/service/windows: no 'environments' in {:current_environment=><Puppet::Node::Environment:70261004253860 @name="*root*" @manifest="no_manifest" @modulepath="" >, :root_environment=><Puppet::Node::Environment:70261004253860 @name="*root*" @manifest="no_manifest" @modulepath="" >} at top of [[0, nil, nil]]
error 2016/12/19 16:50:49: agent.rb:109:in `rescue in handlemsg' /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:55:in `lookup'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:235:in `lookup'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:131:in `module_directories'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:166:in `search_directories'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:95:in `get_file'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:64:in `load_file'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:194:in `load'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1790:in `provider'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1841:in `provide'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/service/windows.rb:3:in `<top (required)>'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:68:in `load'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:68:in `load_file'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:83:in `block in loadall'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:81:in `each'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:81:in `loadall'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:208:in `loadall'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/metatype/manager.rb:126:in `newtype'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/service.rb:10:in `<module:Puppet>'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/service.rb:8:in `<top (required)>'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:68:in `load'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:68:in `load_file'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:194:in `load'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/metatype/manager.rb:171:in `type'
	/opt/puppetlabs/mcollective/plugins/mcollective/util/service/puppetservice.rb:36:in `service_provider'
	/opt/puppetlabs/mcollective/plugins/mcollective/util/service/puppetservice.rb:30:in `status'
	/opt/puppetlabs/mcollective/plugins/mcollective/agent/service.rb:59:in `do_service_action'
	/opt/puppetlabs/mcollective/plugins/mcollective/agent/service.rb:32:in `block in <class:Service>'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/rpc/agent.rb:86:in `handlemsg'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/agents.rb:126:in `block (2 levels) in dispatch'
	/opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
	/opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:33:in `block in catch'
	/opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:33:in `catch'
	/opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:33:in `catch'
	/opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:105:in `timeout'
	/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/agents.rb:125:in `block in dispatch'
~~~

It all comes down to how `choria` initializes puppet in https://github.com/ripienaar/mcollective-choria/blob/master/lib/mcollective/util/choria.rb#L367.

When this is used as is and followed by what the service agent does (in https://github.com/puppetlabs/mcollective-service-agent/blob/master/util/service/puppetservice.rb#L36), it produces the above stacktrace.

Puppet doesn't seem to be correctly initialized.

If I add the following to the choria.rb puppet initialization function, based on what is done in the mcollective-puppet-agent (found here: https://github.com/puppetlabs/mcollective-puppet-agent/blob/master/util/puppet_agent_mgr/mgr_v3.rb#L21):
~~~ruby
            # This check is to keep backwards compatibility
            # with Puppet versions < 3.5.0
            if Puppet.respond_to?(:base_context) \
                && Puppet.respond_to?(:push_context)
              Puppet.push_context(Puppet.base_context(Puppet.settings))
            end
~~~

Then it works correctly :)

Obviously, I'm not using puppet < 3.5.0, so either the comment is plainly inaccurate or there's something else at play here which I haven't found.

Any idea?
Thanks!

**Comment by ripienaar** [comment]
yo @masterzen, I fixed this one in https://github.com/ripienaar/mcollective-choria/pull/84 grab the latest choria module :)

**Comment by masterzen** [comment]
Thanks @ripienaar! you're so fast fixing problems before I report them :)
Closing.
